default_config:

logger:
  default: info
  logs:
    custom_components.midea_dehumidifier_lan: debug
    midea_beautiful: debug

# To debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
