default_config:

logger:
  default: info
  logs:
    homeassistant.helpers.entity_platform: debug
    custom_components.midea_dehumidifier_lan: debug
    midea_beautiful: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy: