name: Repository validation

on:
  push:
  pull_request:
  schedule:
    - cron: "3 14 * * *"

jobs:
  hacs:
    name: Integration Validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
      - uses: "hacs/action@main"
        with:
          category: "integration"
